ARG IMAGE_BASE="ubuntu"
ARG IMAGE_TAG="20.04"

FROM ${IMAGE_BASE}:${IMAGE_TAG}

ARG ETCD_VERSION="v3.4.18"
ARG APISIX_VERSION
ARG IMAGE_BASE
ARG IMAGE_TAG

ENV RUNNING_ETCD_VERSION=${ETCD_VERSION}

COPY ./output/apisix_${APISIX_VERSION}-0~${IMAGE_BASE}${IMAGE_TAG}_arm64.deb /apisix_${APISIX_VERSION}-0~${IMAGE_BASE}${IMAGE_TAG}_arm64.deb
COPY ./utils/install-common.sh /install-common.sh
COPY ./utils/build-common.sh /build-common.sh
COPY ./build-apisix-base.sh /build-apisix-base.sh

RUN cd / && version=latest ./build-common.sh build_apisix_base_deb \
    && ln -s /usr/local/openresty/bin/openresty /usr/local/bin/openresty

# install etcd
RUN apt-get update \
    && apt-get install -y wget \
    && /install-common.sh install_etcd

# install apisix
RUN set -x \
    && apt install -y libldap2-dev libpcre3 libpcre3-dev \
    && dpkg -i /apisix_${APISIX_VERSION}-0~${IMAGE_BASE}${IMAGE_TAG}_arm64.deb

# start etcd and test
CMD ["sh", "-c", "(ETCD_UNSUPPORTED_ARCH=arm64 nohup etcd-$RUNNING_ETCD_VERSION-linux-arm64/etcd >/tmp/etcd.log 2>&1 &) && sleep 10 && apisix start && sleep 3600"]

EXPOSE 9080 9443
