#!/usr/bin/expect -f
set timeout 2
set passphrase [lindex $argv 0]

spawn reprepro -b [lindex $argv 1] [lindex $argv 2] [lindex $argv 3] [lindex $argv 4]
expect {
        "*passphrase:*" {
                send -- "$passphrase\r"
        }
}
expect {
        "*passphrase:*" {
                send -- "$passphrase\r"
        }
}
interact